### ISSUE TITLE
clarifications

### ISSUE THREAD

**Issue by Dreaming-Codes** [SWRT-dev/rtax89x#2]
Hi, I'm looking for a custom firmware for my rt-ax89x and this looks like what I'm looking for but unfortunately I don't understand Chinese and Google translate doesn't help.
Can you please tell which additional features and which fewer (if any) there are in this compared to the original?
Thanks from Italy.

**Comment by sim-13** [comment]
Здравствуйте, Lorenzo.


Вы писали 12 декабря 2021 г., 18:38:55:

> Hi, I'm looking for a custom firmware for my rt-ax89x and this looks like what I'm looking for but unfortunately I don't understand Chinese and Google translate doesn't help.
> Can you please tell which additional features and which fewer (if any) there are in this compared to the original?
> Thanks from Italy.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

Hello. This firmware is based on firmware from Merlin. The main differences between these: added Soft Center and Entware, the rest is small stuff. Personally, I sew on top of the original one with all the settings saved and vice versa - all the settings are saved... so try it.

-- 
С уважением,
 Sim                         ***@***.***

**Comment by Dreaming-Codes** [comment]
> Здравствуйте, Lorenzo.
> 
> 
> Вы писали 12 декабря 2021 г., 18:38:55:
> 
> > Hi, I'm looking for a custom firmware for my rt-ax89x and this looks like what I'm looking for but unfortunately I don't understand Chinese and Google translate doesn't help.
> > Can you please tell which additional features and which fewer (if any) there are in this compared to the original?
> > Thanks from Italy.
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> Hello. This firmware is based on firmware from Merlin. The main differences between these: added Soft Center and Entware, the rest is small stuff. Personally, I sew on top of the original one with all the settings saved and vice versa - all the settings are saved... so try it.
> 
> -- 
> С уважением,
>  Sim                         ***@***.***

Okay, thanks for the quick reply. After in case to return to the original firmware where can I find it?
