### ISSUE TITLE
 ipv6 slaac

### ISSUE THREAD

**Issue by mnlk2** [SWRT-dev/rtax89x#4]
look like ipv6 slaac dont work correctly,   my tv box need ipv6 slaac to work, but it dont work with the last version.    it work with the old version and with original firmware, but not in your last firmware.

**Comment by paldier** [comment]
last firmware? code?

**Comment by mnlk2** [comment]
oh, not last commit, i dont saw you just updated it, but this commit: [Merged with 386.47027]

**Comment by mnlk2** [comment]
i'll try with new code update

**Comment by paldier** [comment]
I found out that ipv6 dns is missing, maybe that's the reason.
I will try to fix it.

**Comment by mnlk2** [comment]
yes mb it this, i have sometime a dns error on my tv

**Comment by paldier** [comment]
The last code has solved this problem.
Disable smartdns and reboot, ipv6 will work fine.
http://router.asus.com/Advanced_SmartDNS_Content.asp

**Comment by mnlk2** [comment]
ok, i'll try this on week end :)

**Comment by mnlk2** [comment]
for now look like it's ok.   if i add my isp dns in the list i can leave smart dns right? or it's only for china user?

**Comment by paldier** [comment]
It works for everyone, isp's dns is automatically added to config, only ipv4 dns. 
You can add your favorite dns, both ipv4 and ipv6 are supported.

**Comment by mnlk2** [comment]
ok, i'll try , thank  you for your work

**Comment by mnlk2** [comment]
it's ok witrh smartdns off, otherwise tv dont work
